import { Link } from "react-router-dom";
import { ArrowRight, ShieldCheck, HeartHandshake, CarFront, MapPin } from "lucide-react";

export default function About() {
  return <div>
    <section className="relative overflow-hidden bg-ink text-white"><img src="https://images.unsplash.com/photo-1525609004556-c46c7cf7cf81?auto=format&fit=crop&w=2200&q=85" alt="" className="absolute inset-0 h-full w-full object-cover opacity-35" /><div className="absolute inset-0 bg-ink/65" /><div className="container-page relative py-20 sm:py-28"><p className="eyebrow">About HRR Travels</p><h1 className="mt-3 max-w-3xl font-display text-5xl font-extrabold sm:text-6xl">A better way to experience Vizag.</h1><p className="mt-6 max-w-2xl text-sm leading-7 text-white/65">We make self-drive rentals simple, transparent and comfortable with a carefully maintained fleet.</p></div></section>
    <section className="container-page py-16 sm:py-20"><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><div><p className="eyebrow">Our Story</p><h2 className="section-title mt-2">Built around freedom on the road.</h2><p className="mt-5 text-sm leading-7 text-muted">HRR Travels is designed for customers who want the flexibility of driving their own car without the long-term commitment of ownership. Our focus is simple: reliable vehicles, clear rental terms and helpful support.</p><p className="mt-4 text-sm leading-7 text-muted">Whether you're exploring Visakhapatnam, planning a weekend trip or need a car for a few days, our fleet is built to fit different travel needs.</p><Link to="/cars" className="btn-gold mt-7">Explore Our Fleet <ArrowRight size={16}/></Link></div><img src="https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1400&q=85" alt="" className="h-[420px] w-full rounded-3xl object-cover"/></div></section>
    <section className="bg-white py-16"><div className="container-page"><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4">{[[CarFront,"Quality Fleet","Clean, reliable vehicles prepared for every booking."],[ShieldCheck,"Trust & Safety","Clear terms and document verification."],[HeartHandshake,"Customer First","Support that stays available when you need it."],[MapPin,"Local Expertise","A rental experience designed around Vizag."]].map(([Icon,t,d])=><div className="card p-6" key={t}><Icon className="text-goldDark" size={25}/><h3 className="mt-5 font-display text-lg font-bold">{t}</h3><p className="mt-2 text-sm leading-6 text-muted">{d}</p></div>)}</div></div></section>
  </div>;
}